name: "Bug Report"
description: "버그 제보 (외부 기여자 포함)"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        버그 제보 감사합니다.
        팀원이 아니어도 누구나 작성할 수 있으며, 재현 가능한 정보가 많을수록 처리 속도가 빨라집니다.

  - type: input
    id: summary
    attributes:
      label: 요약
      placeholder: 어떤 문제가 발생했는지 한 줄로 작성
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      options:
        - "S1 - 치명적 (주요 기능 사용 불가)"
        - "S2 - 높음 (핵심 흐름에 큰 영향)"
        - "S3 - 보통 (우회 가능)"
        - "S4 - 낮음 (경미한 불편)"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 절차
      description: 재현 가능한 순서로 작성해 주세요.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
      placeholder: 원래 기대한 동작
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
      placeholder: 실제로 발생한 동작
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: 영향 범위
      options:
        - "popup"
        - "options"
        - "background/service worker"
        - "redirect/locking logic"
        - "storage/state"
        - "기타"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 확장 버전
      placeholder: 예) v1.0.0
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 환경
      placeholder: 예) Chrome 122 / Windows 11
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 로그/스크린샷
      placeholder: 콘솔 로그, 녹화, 스크린샷 등

  - type: textarea
    id: acceptance
    attributes:
      label: 완료 기준 (선택)
      description: 이 이슈가 해결되었다고 볼 수 있는 기준
      placeholder: |
        - [ ] ...
        - [ ] ...

  - type: textarea
    id: extra
    attributes:
      label: 추가 정보
      placeholder: 관련 이슈/PR/레퍼런스 링크
